// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyA1wZCU_dTCmBlsGzZ1QfxGgrlD3Fj3_DU',
    // appId: '1:505782275497:web:1ee545595236285b0d08b8',
    // messagingSenderId: '505782275497',
    // projectId: 'asfire-852f0',
    // authDomain: 'asfire-852f0.firebaseapp.com',
    // storageBucket: 'asfire-852f0.firebasestorage.app',
    // measurementId: 'G-NDL985L2N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyBvXn7B0vXq6Hf-ipeaWndCiVP5LrvT1l0',
    // appId: '1:505782275497:android:58b5ccf194f1c2be0d08b8',
    // messagingSenderId: '505782275497',
    // projectId: 'asfire-852f0',
    // storageBucket: 'asfire-852f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    //apiKey: 'AIzaSyCr4zL1xIARP52rvX0NUoVDP95qpF_-ms0',
    // appId: '1:505782275497:ios:6bc9cab4ef5e578d0d08b8',
    // messagingSenderId: '505782275497',
    // projectId: 'asfire-852f0',
    // storageBucket: 'asfire-852f0.firebasestorage.app',
    // iosBundleId: 'com.example.assign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    // apiKey: 'AIzaSyCr4zL1xIARP52rvX0NUoVDP95qpF_-ms0',
    // appId: '1:505782275497:ios:6bc9cab4ef5e578d0d08b8',
    // messagingSenderId: '505782275497',
    // projectId: 'asfire-852f0',
    // storageBucket: 'asfire-852f0.firebasestorage.app',
    // iosBundleId: 'com.example.assign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    // apiKey: 'AIzaSyA1wZCU_dTCmBlsGzZ1QfxGgrlD3Fj3_DU',
    // appId: '1:505782275497:web:f1f8a14ace714f1f0d08b8',
    // messagingSenderId: '505782275497',
    // projectId: 'asfire-852f0',
    // authDomain: 'asfire-852f0.firebaseapp.com',
    // storageBucket: 'asfire-852f0.firebasestorage.app',
    // measurementId: 'G-JBMXNHV0D9',
  );
}
